//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaseEntity> BaseEntities { get; set; }
        public virtual DbSet<BaseEntity> Movies { get; set; }
        public virtual DbSet<BaseEntity> MovieExtraProperties { get; set; }
        public virtual DbSet<BaseEntity> Photos { get; set; }
        public virtual DbSet<BaseEntity> PhotoExtraProperties { get; set; }
        public virtual DbSet<BaseEntity> People { get; set; }
    }
}
